// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RarApiConsole.providers;

#nullable disable

namespace RarApiConsole.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RarApiConsole.dataObjects.DoCandidate", b =>
                {
                    b.Property<int>("object_key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("object_key"));

                    b.Property<int>("fk_profile")
                        .HasColumnType("int");

                    b.Property<int>("profileobject_key")
                        .HasColumnType("integer");

                    b.Property<DateTime>("referred_at")
                        .HasColumnType("timestamp");

                    b.HasKey("object_key");

                    b.HasIndex("fk_profile");

                    b.HasIndex("profileobject_key");

                    b.ToTable("candidates", "public");
                });

            modelBuilder.Entity("RarApiConsole.dataObjects.DoProfile", b =>
                {
                    b.Property<int>("object_key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("object_key"));

                    b.Property<string>("address")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("email")
                        .HasColumnType("varchar(40)");

                    b.Property<string>("initials")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("name")
                        .HasColumnType("varchar(40)");

                    b.Property<string>("phone_number")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("surname")
                        .HasColumnType("varchar(70)");

                    b.HasKey("object_key");

                    b.ToTable("profiles", "public");
                });

            modelBuilder.Entity("RarApiConsole.dataObjects.DoReferral", b =>
                {
                    b.Property<int>("object_key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("object_key"));

                    b.Property<int>("candidateobject_key")
                        .HasColumnType("integer");

                    b.Property<DateTime>("creation_dt")
                        .HasColumnType("timestamp");

                    b.Property<int>("fk_candidate")
                        .HasColumnType("int");

                    b.Property<int>("fk_scoreboard")
                        .HasColumnType("int");

                    b.Property<int>("fk_task")
                        .HasColumnType("int");

                    b.Property<int>("fk_user")
                        .HasColumnType("int");

                    b.Property<DateTime>("modification_dt")
                        .HasColumnType("timestamp");

                    b.Property<int>("scoreboardobject_key")
                        .HasColumnType("integer");

                    b.Property<int>("taskobject_key")
                        .HasColumnType("integer");

                    b.Property<int>("userobject_key")
                        .HasColumnType("integer");

                    b.HasKey("object_key");

                    b.HasIndex("candidateobject_key");

                    b.HasIndex("fk_candidate");

                    b.HasIndex("fk_scoreboard");

                    b.HasIndex("fk_task");

                    b.HasIndex("fk_user");

                    b.HasIndex("scoreboardobject_key");

                    b.HasIndex("taskobject_key");

                    b.HasIndex("userobject_key");

                    b.ToTable("referrals", "public");
                });

            modelBuilder.Entity("RarApiConsole.dataObjects.DoReward", b =>
                {
                    b.Property<int>("object_key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("object_key"));

                    b.Property<DateTime>("award_dt")
                        .HasColumnType("timestamp");

                    b.Property<int>("fk_user")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("userobject_key")
                        .HasColumnType("integer");

                    b.HasKey("object_key");

                    b.HasIndex("fk_user");

                    b.HasIndex("userobject_key");

                    b.ToTable("rewards", "public");
                });

            modelBuilder.Entity("RarApiConsole.dataObjects.DoScoreboard", b =>
                {
                    b.Property<int>("object_key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("object_key"));

                    b.Property<DateTime?>("end_dt")
                        .HasColumnType("timestamp");

                    b.Property<int>("fk_user")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.Property<DateTime>("start_dt")
                        .HasColumnType("timestamp");

                    b.Property<int>("userobject_key")
                        .HasColumnType("integer");

                    b.HasKey("object_key");

                    b.HasIndex("fk_user");

                    b.HasIndex("userobject_key");

                    b.ToTable("scoreboards", "public");
                });

            modelBuilder.Entity("RarApiConsole.dataObjects.DoTask", b =>
                {
                    b.Property<int>("object_key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("object_key"));

                    b.Property<string>("description")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("points")
                        .HasColumnType("int");

                    b.HasKey("object_key");

                    b.ToTable("tasks", "public");
                });

            modelBuilder.Entity("RarApiConsole.dataObjects.DoUser", b =>
                {
                    b.Property<int>("object_key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("object_key"));

                    b.Property<DateTime>("creation_dt")
                        .HasColumnType("timestamp");

                    b.Property<int?>("fk_profile")
                        .HasColumnType("int");

                    b.Property<DateTime>("modification_dt")
                        .HasColumnType("timestamp");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("profileobject_key")
                        .HasColumnType("integer");

                    b.Property<int>("recruiter")
                        .HasColumnType("int");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("object_key");

                    b.HasIndex("fk_profile");

                    b.HasIndex("profileobject_key");

                    b.ToTable("users", "public");
                });

            modelBuilder.Entity("RarApiConsole.dataObjects.DoCandidate", b =>
                {
                    b.HasOne("RarApiConsole.dataObjects.DoProfile", null)
                        .WithMany()
                        .HasForeignKey("fk_profile")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RarApiConsole.dataObjects.DoProfile", "profile")
                        .WithMany()
                        .HasForeignKey("profileobject_key")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("profile");
                });

            modelBuilder.Entity("RarApiConsole.dataObjects.DoReferral", b =>
                {
                    b.HasOne("RarApiConsole.dataObjects.DoCandidate", "candidate")
                        .WithMany()
                        .HasForeignKey("candidateobject_key")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RarApiConsole.dataObjects.DoCandidate", null)
                        .WithMany()
                        .HasForeignKey("fk_candidate")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RarApiConsole.dataObjects.DoScoreboard", null)
                        .WithMany()
                        .HasForeignKey("fk_scoreboard")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RarApiConsole.dataObjects.DoTask", null)
                        .WithMany()
                        .HasForeignKey("fk_task")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RarApiConsole.dataObjects.DoUser", null)
                        .WithMany()
                        .HasForeignKey("fk_user")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RarApiConsole.dataObjects.DoScoreboard", "scoreboard")
                        .WithMany()
                        .HasForeignKey("scoreboardobject_key")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RarApiConsole.dataObjects.DoTask", "task")
                        .WithMany()
                        .HasForeignKey("taskobject_key")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RarApiConsole.dataObjects.DoUser", "user")
                        .WithMany()
                        .HasForeignKey("userobject_key")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("candidate");

                    b.Navigation("scoreboard");

                    b.Navigation("task");

                    b.Navigation("user");
                });

            modelBuilder.Entity("RarApiConsole.dataObjects.DoReward", b =>
                {
                    b.HasOne("RarApiConsole.dataObjects.DoUser", null)
                        .WithMany()
                        .HasForeignKey("fk_user")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RarApiConsole.dataObjects.DoUser", "user")
                        .WithMany()
                        .HasForeignKey("userobject_key")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("RarApiConsole.dataObjects.DoScoreboard", b =>
                {
                    b.HasOne("RarApiConsole.dataObjects.DoUser", null)
                        .WithMany()
                        .HasForeignKey("fk_user")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RarApiConsole.dataObjects.DoUser", "user")
                        .WithMany()
                        .HasForeignKey("userobject_key")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("RarApiConsole.dataObjects.DoUser", b =>
                {
                    b.HasOne("RarApiConsole.dataObjects.DoProfile", null)
                        .WithMany()
                        .HasForeignKey("fk_profile");

                    b.HasOne("RarApiConsole.dataObjects.DoProfile", "profile")
                        .WithMany()
                        .HasForeignKey("profileobject_key");

                    b.Navigation("profile");
                });
#pragma warning restore 612, 618
        }
    }
}
