#!/bin/bash

function readJson {  
  UNAMESTR=`uname`
  if [[ "$UNAMESTR" == 'Linux' ]]; then
    SED_EXTENDED='-r'
  elif [[ "$UNAMESTR" == 'Darwin' ]]; then
    SED_EXTENDED='-E'
  fi; 
  VALUE=`grep -m 1 "\"${2}\"" ${1} | sed ${SED_EXTENDED} 's/^ *//;s/.*: *"//;s/",?//'`
  if [ ! "$VALUE" ]; then
    echo "Error: Cannot find \"${2}\" in ${1}" >&2;
    exit 1;
  else
    echo $VALUE ;
  fi; 
}

red=`tput setaf 1`
green=`tput setaf 2`
yellow=`tput setaf 3`
reset=`tput sgr0`
line='--------'
NOW=$(date +"%d-%m-%Y %H:%M")
VERSION=`readJson package.json version` || exit 1;  

#chmod a+x rar.sh

if [[ $1 = '' ]]; then
    echo "${green}=== R.A.R. (Referral Applicatie Recruitment) ===${reset}"
    echo "${green}==== Running Version ${VERSION} ====${reset}"
    echo "Run ${yellow}./rar serve${reset} to update & start the server and web application."
    echo "On the first run, this will also install all dependencies, set up the database and build the application."
fi

if [[ $1 = 'serve' ]]; then
    npm install
    npm run dev &
    sleep 1 # Wait for the local server to start
    open http://127.0.0.1:5173/ &
fi
